name: Static Site CI

on:
  push:
    branches:
      - main
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Placeholder build step
        run: echo "Static website - no build needed"

      - name: Skip tests
        run: echo "No tests available"
